FROM mhart/alpine-node:12 AS builder
WORKDIR /app
COPY . .
RUN yarn install
ENV NODE_ENV production
RUN yarn build

# And then copy over node_modules, etc from that stage to the smaller base image
FROM mhart/alpine-node:12
WORKDIR /app

COPY --from=builder /app/yarn.lock ./yarn.lock
COPY --from=builder /app/package.json ./package.json
ENV NODE_ENV production
RUN yarn install --no-cache --production
COPY --from=builder /app/dist ./dist
EXPOSE 4000
CMD [ "yarn","start"]
